// كتالوج شامل لكل الكيانات المتاحة في النظام مع حقولها الهامة وتسميات عربية
// يُستخدم في صفحة الأوامر الذكية لبناء القوائم والأعمدة وتصدير Excel

export const ENTITIES_CATALOG = [
  {
    value: 'Employee',
    label: 'الموظفين',
    icon: '👥',
    fields: [
      { key: 'full_name_arabic', label: 'الاسم الكامل' },
      { key: 'full_name_english', label: 'الاسم بالإنجليزي' },
      { key: 'رقم_الموظف', label: 'رقم الموظف' },
      { key: 'رقم_الهوية', label: 'رقم الهوية' },
      { key: 'birth_date', label: 'تاريخ الميلاد' },
      { key: 'gender', label: 'الجنس' },
      { key: 'nationality', label: 'الجنسية' },
      { key: 'phone', label: 'الجوال' },
      { key: 'email', label: 'البريد الإلكتروني' },
      { key: 'position', label: 'التخصص / الوظيفة' },
      { key: 'department', label: 'القسم' },
      { key: 'job_category', label: 'ملاك الوظيفة' },
      { key: 'job_category_type', label: 'فئة الوظيفة' },
      { key: 'qualification', label: 'المؤهل' },
      { key: 'rank', label: 'المرتبة' },
      { key: 'level', label: 'المستوى' },
      { key: 'grade', label: 'الدرجة' },
      { key: 'hire_date', label: 'تاريخ التعيين' },
      { key: 'start_work_date', label: 'تاريخ المباشرة' },
      { key: 'contract_type', label: 'نوع العقد' },
      { key: 'contract_end_date', label: 'انتهاء العقد' },
      { key: 'المركز_الصحي', label: 'المركز الصحي' },
      { key: 'special_roles', label: 'الأدوار الخاصة' },
      { key: 'assigned_tasks', label: 'المهام المكلف بها' },
      { key: '__combined_roles', label: 'مهام إضافية (قيادية/إشرافية)' },
      { key: 'scfhs_classification', label: 'تصنيف الهيئة' },
    ],
  },
  {
    value: 'HealthCenter',
    label: 'المراكز الصحية',
    icon: '🏥',
    fields: [
      { key: 'اسم_المركز', label: 'اسم المركز' },
      { key: 'اسم_المركز_انجليزي', label: 'الاسم بالإنجليزي' },
      { key: 'seha_id', label: 'رقم صحة' },
      { key: 'المدير', label: 'المدير' },
      { key: 'نائب_المدير', label: 'نائب المدير' },
      { key: 'المشرف_الفني', label: 'المشرف الفني' },
      { key: 'الموقع', label: 'الموقع' },
      { key: 'موقع_الخريطة', label: 'موقع الخريطة' },
      { key: 'ايميل_المركز', label: 'البريد الإلكتروني' },
      { key: 'هاتف_المركز', label: 'الهاتف' },
      { key: 'فاكس_المركز', label: 'الفاكس' },
      { key: 'رقم_الجوال', label: 'الجوال' },
      { key: 'رقم_الشريحة', label: 'رقم الشريحة' },
      { key: 'رقم_الهاتف_الثابت', label: 'الهاتف الثابت' },
      { key: 'حالة_المركز', label: 'حالة المركز' },
      { key: 'حالة_التشغيل', label: 'حالة التشغيل' },
      { key: 'قيمة_عقد_الايجار', label: 'قيمة الإيجار' },
      { key: 'اسم_المؤجر', label: 'اسم المؤجر' },
      { key: 'هاتف_المؤجر', label: 'هاتف المؤجر' },
      { key: 'تاريخ_بداية_العقد', label: 'بداية العقد' },
      { key: 'تاريخ_انتهاء_العقد', label: 'انتهاء العقد' },
      { key: 'رقم_العقد', label: 'رقم العقد' },
      { key: 'معتمد_سباهي', label: 'معتمد سباهي' },
      { key: 'تاريخ_اعتماد_سباهي', label: 'تاريخ اعتماد سباهي' },
      { key: 'مركز_نائي', label: 'مركز نائي' },
      { key: 'بدل_نأي', label: 'بدل النأي' },
      { key: 'ساعات_الدوام', label: 'ساعات الدوام' },
      { key: 'عدد_الموظفين_الكلي', label: 'عدد الموظفين' },
      { key: 'الخدمات_المقدمة', label: 'الخدمات المقدمة' },
      { key: 'سيارة_خدمات.متوفرة', label: 'سيارة الخدمات - متوفرة؟' },
      { key: 'سيارة_خدمات.رقم_اللوحة_عربي', label: 'سيارة الخدمات - اللوحة عربي' },
      { key: 'سيارة_خدمات.رقم_اللوحة_انجليزي', label: 'سيارة الخدمات - اللوحة إنجليزي' },
      { key: 'سيارة_خدمات.رقم_الهيكل', label: 'سيارة الخدمات - رقم الهيكل' },
      { key: 'سيارة_خدمات.الرقم_التسلسلي', label: 'سيارة الخدمات - الرقم التسلسلي' },
      { key: 'سيارة_خدمات.نوع_السيارة', label: 'سيارة الخدمات - النوع' },
      { key: 'سيارة_خدمات.موديل', label: 'سيارة الخدمات - الموديل' },
      { key: 'سيارة_خدمات.نوع_الوقود', label: 'سيارة الخدمات - الوقود' },
      { key: 'سيارة_خدمات.تبعية_المحطة', label: 'سيارة الخدمات - تبعية المحطة' },
      { key: 'سيارة_خدمات.حالة_السيارة', label: 'سيارة الخدمات - الحالة' },
      { key: 'سيارة_خدمات.المسافة_المقطوعة', label: 'سيارة الخدمات - المسافة' },
      { key: 'سيارة_خدمات.اسم_السائق', label: 'سيارة الخدمات - السائق' },
      { key: 'سيارة_خدمات.رخصة_السائق', label: 'سيارة الخدمات - رخصة السائق' },
      { key: 'سيارة_خدمات.تاريخ_آخر_صيانة', label: 'سيارة الخدمات - آخر صيانة' },
      { key: 'سيارة_خدمات.تاريخ_انتهاء_الرخصة', label: 'سيارة الخدمات - انتهاء الرخصة' },
      { key: 'سيارة_خدمات.تاريخ_انتهاء_التأمين', label: 'سيارة الخدمات - انتهاء التأمين' },
      { key: 'سيارة_اسعاف.متوفرة', label: 'سيارة الإسعاف - متوفرة؟' },
      { key: 'سيارة_اسعاف.رقم_اللوحة_عربي', label: 'سيارة الإسعاف - اللوحة عربي' },
      { key: 'سيارة_اسعاف.رقم_اللوحة_انجليزي', label: 'سيارة الإسعاف - اللوحة إنجليزي' },
      { key: 'سيارة_اسعاف.رقم_الهيكل', label: 'سيارة الإسعاف - رقم الهيكل' },
      { key: 'سيارة_اسعاف.الرقم_التسلسلي', label: 'سيارة الإسعاف - الرقم التسلسلي' },
      { key: 'سيارة_اسعاف.نوع_السيارة', label: 'سيارة الإسعاف - النوع' },
      { key: 'سيارة_اسعاف.موديل', label: 'سيارة الإسعاف - الموديل' },
      { key: 'سيارة_اسعاف.نوع_الوقود', label: 'سيارة الإسعاف - الوقود' },
      { key: 'سيارة_اسعاف.حالة_السيارة', label: 'سيارة الإسعاف - الحالة' },
      { key: 'سيارة_اسعاف.مجهزة_بالكامل', label: 'سيارة الإسعاف - مجهزة بالكامل' },
      { key: 'سيارة_اسعاف.اسم_السائق', label: 'سيارة الإسعاف - السائق' },
      { key: 'سيارة_اسعاف.رخصة_السائق', label: 'سيارة الإسعاف - رخصة السائق' },
      { key: 'سيارة_اسعاف.تاريخ_آخر_صيانة', label: 'سيارة الإسعاف - آخر صيانة' },
      { key: 'سيارة_اسعاف.تاريخ_انتهاء_الرخصة', label: 'سيارة الإسعاف - انتهاء الرخصة' },
      { key: 'سيارة_اسعاف.تاريخ_انتهاء_التأمين', label: 'سيارة الإسعاف - انتهاء التأمين' },
    ],
    // مجموعات لتسهيل الاختيار السريع
    presets: [
      { label: '🚗 سيارة الخدمات (شامل)', fields: ['اسم_المركز', 'سيارة_خدمات.رقم_اللوحة_عربي', 'سيارة_خدمات.نوع_السيارة', 'سيارة_خدمات.موديل', 'سيارة_خدمات.حالة_السيارة', 'سيارة_خدمات.اسم_السائق', 'سيارة_خدمات.تاريخ_انتهاء_الرخصة'] },
      { label: '🚑 سيارة الإسعاف (شامل)', fields: ['اسم_المركز', 'سيارة_اسعاف.رقم_اللوحة_عربي', 'سيارة_اسعاف.نوع_السيارة', 'سيارة_اسعاف.موديل', 'سيارة_اسعاف.حالة_السيارة', 'سيارة_اسعاف.اسم_السائق', 'سيارة_اسعاف.مجهزة_بالكامل'] },
      { label: '👔 بيانات المدراء', fields: ['اسم_المركز', 'المدير', 'نائب_المدير', 'المشرف_الفني', 'رقم_الجوال', 'ايميل_المركز'] },
      { label: '📍 معلومات الاتصال', fields: ['اسم_المركز', 'الموقع', 'هاتف_المركز', 'رقم_الجوال', 'ايميل_المركز', 'فاكس_المركز'] },
      { label: '🏢 بيانات عقود الإيجار', fields: ['اسم_المركز', 'حالة_المركز', 'اسم_المؤجر', 'هاتف_المؤجر', 'قيمة_عقد_الايجار', 'تاريخ_بداية_العقد', 'تاريخ_انتهاء_العقد'] },
      { label: '✅ الاعتمادات', fields: ['اسم_المركز', 'معتمد_سباهي', 'تاريخ_اعتماد_سباهي', 'مركز_نائي'] },
    ],
  },
  {
    value: 'MedicalEquipment',
    label: 'الأجهزة الطبية',
    icon: '🔬',
    fields: [
      { key: 'equipment_name', label: 'اسم الجهاز' },
      { key: 'health_center_name', label: 'المركز الصحي' },
      { key: 'department', label: 'القسم' },
      { key: 'status', label: 'الحالة' },
      { key: 'serial_number', label: 'الرقم التسلسلي' },
      { key: 'manufacturer', label: 'الشركة المصنعة' },
      { key: 'model', label: 'الموديل' },
      { key: 'quantity', label: 'الكمية' },
    ],
  },
  {
    value: 'EquipmentRequest',
    label: 'طلبات الأجهزة',
    icon: '📋',
    fields: [
      { key: 'device_name', label: 'اسم الجهاز' },
      { key: 'device_code', label: 'رقم البند' },
      { key: 'health_center_name', label: 'المركز' },
      { key: 'department', label: 'القسم' },
      { key: 'request_type', label: 'نوع الطلب' },
      { key: 'classification', label: 'التصنيف' },
      { key: 'priority', label: 'الأهمية' },
      { key: 'requested_quantity', label: 'الكمية المطلوبة' },
      { key: 'quantity_in_department', label: 'الكمية بالقسم' },
      { key: 'quantity_in_site', label: 'الكمية بالموقع' },
      { key: 'requester_name', label: 'مقدم الطلب' },
      { key: 'status', label: 'الحالة' },
    ],
  },
  {
    value: 'DeficiencyReport',
    label: 'نواقص المراكز',
    icon: '⚠️',
    fields: [
      { key: 'health_center', label: 'المركز' },
      { key: 'deficiency_type', label: 'نوع النقص' },
      { key: 'description', label: 'الوصف' },
      { key: 'report_date', label: 'تاريخ البلاغ' },
      { key: 'status', label: 'الحالة' },
    ],
  },
  {
    value: 'Leave',
    label: 'الإجازات',
    icon: '🗓️',
    fields: [
      { key: 'employee_name', label: 'اسم الموظف' },
      { key: 'employee_id', label: 'رقم الموظف' },
      { key: 'health_center', label: 'المركز الصحي' },
      { key: 'leave_type', label: 'نوع الإجازة' },
      { key: 'start_date', label: 'تاريخ البداية' },
      { key: 'end_date', label: 'تاريخ النهاية' },
      { key: 'mubashara_date', label: 'تاريخ المباشرة' },
      { key: 'days_count', label: 'عدد الأيام' },
      { key: 'status', label: 'الحالة' },
    ],
  },
  {
    value: 'Assignment',
    label: 'التكاليف',
    icon: '📝',
    fields: [
      { key: 'employee_name', label: 'اسم الموظف' },
      { key: 'employee_job_id', label: 'الرقم الوظيفي' },
      { key: 'employee_position', label: 'الوظيفة' },
      { key: 'from_health_center', label: 'مركز العمل الأصلي' },
      { key: 'assigned_to_health_center', label: 'المركز المكلف به' },
      { key: 'start_date', label: 'تاريخ البداية' },
      { key: 'end_date', label: 'تاريخ النهاية' },
      { key: 'duration_days', label: 'المدة (أيام)' },
      { key: 'issue_date', label: 'تاريخ الإصدار' },
      { key: 'approval_status', label: 'حالة الاعتماد' },
      { key: 'status', label: 'الحالة' },
    ],
  },
  {
    value: 'CenterDocument',
    label: 'مستندات المراكز',
    icon: '📄',
    fields: [
      { key: 'center_name', label: 'المركز' },
      { key: 'document_title', label: 'عنوان المستند' },
      { key: 'document_type', label: 'نوع المستند' },
      { key: 'document_number', label: 'رقم المستند' },
      { key: 'document_date', label: 'التاريخ' },
      { key: 'expiry_date', label: 'تاريخ الانتهاء' },
      { key: 'is_active', label: 'نشط' },
    ],
  },
  {
    value: 'ArchivedEmployee',
    label: 'الموظفون المؤرشفون',
    icon: '📦',
    fields: [
      { key: 'full_name_arabic', label: 'الاسم' },
      { key: 'رقم_الموظف', label: 'رقم الموظف' },
      { key: 'رقم_الهوية', label: 'رقم الهوية' },
      { key: 'position', label: 'الوظيفة' },
      { key: 'المركز_الصحي', label: 'المركز السابق' },
      { key: 'archive_type', label: 'نوع الأرشفة' },
      { key: 'archive_date', label: 'تاريخ الأرشفة' },
      { key: 'archive_reason', label: 'السبب' },
      { key: 'new_workplace', label: 'مكان العمل الجديد' },
    ],
  },
  {
    value: 'AllowanceRequest',
    label: 'طلبات البدلات',
    icon: '💰',
    fields: [
      { key: 'employee_name', label: 'اسم الموظف' },
      { key: 'employee_number', label: 'رقم الموظف' },
      { key: 'position', label: 'الوظيفة' },
      { key: 'department', label: 'القسم' },
      { key: 'allowance_type', label: 'نوع البدل' },
      { key: 'status', label: 'الحالة' },
    ],
  },
  {
    value: 'ApprovalRequest',
    label: 'طلبات الاعتماد',
    icon: '✅',
    fields: [
      { key: 'title', label: 'العنوان' },
      { key: 'request_type', label: 'نوع الطلب' },
      { key: 'status', label: 'الحالة' },
      { key: 'created_date', label: 'تاريخ الإنشاء' },
    ],
  },
  {
    value: 'FormSubmission',
    label: 'النماذج المقدمة',
    icon: '🗒️',
    fields: [
      { key: 'form_template_title', label: 'النموذج' },
      { key: 'submitted_by_employee_name', label: 'مقدم النموذج' },
      { key: 'submission_date', label: 'تاريخ التقديم' },
      { key: 'status', label: 'الحالة' },
    ],
  },
];

export const getEntityByValue = (value) => ENTITIES_CATALOG.find((e) => e.value === value);

export const getFieldLabel = (entityValue, fieldKey) => {
  const entity = getEntityByValue(entityValue);
  if (!entity) return fieldKey.replace(/_/g, ' ');
  const field = entity.fields.find((f) => f.key === fieldKey);
  return field ? field.label : fieldKey.replace(/_/g, ' ');
};